# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
