# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_pub_time'),
    ]

    operations = [

    ]
